// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RewriteHistory(arg1:string,arg2:Record<string, main.Identity>):Promise<void>;

export function ScanRepository(arg1:string):Promise<main.ScanResult>;

export function SelectRepository():Promise<string>;
